# Identidad del proyecto
sonar.projectKey=petsalud-backend
sonar.projectName=PetSalud Backend
sonar.projectVersion=1.0.0

# Codificación
sonar.sourceEncoding=UTF-8

# Rutas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**/*.js,**/*.test.js,**/*.spec.js

sonar.exclusions=coverage/**,node_modules/**,**/*.md,**/*.json,**/*.yml,**/*.yaml,**/*.lock,**/*.sql,**/migrations/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
